# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jmylchreest/histui

linters-settings:
  errcheck:
    check-blank: false
  misspell:
    locale: US
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-dirs:
    - specs
  exclude-rules:
    # Ignore test files for some linters
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    # Ignore test helper functions
    - path: testutil
      linters:
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 3
